//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Allowance()
        {
            this.StaffJoinAllowances = new HashSet<StaffJoinAllowance>();
        }
    
        public int id { get; set; }
        public string nameAllowance { get; set; }
        public string description { get; set; }
        public Nullable<double> money { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffJoinAllowance> StaffJoinAllowances { get; set; }
    }
}
