//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int id { get; set; }
        public Nullable<System.DateTime> signDay { get; set; }
        public string mainContent { get; set; }
        public Nullable<int> signCount { get; set; }
        public string limitation { get; set; }
        public string coSalary { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<double> salary { get; set; }
        public string contractNumber { get; set; }
        public Nullable<System.DateTime> startDay { get; set; }
        public Nullable<System.DateTime> endDay { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
