//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuChuyen
    {
        public int id { get; set; }
        public string SoDC { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<System.DateTime> createDay { get; set; }
        public string Ghichu { get; set; }
        public string Lydo { get; set; }
        public Nullable<int> idRoom { get; set; }
        public Nullable<int> idRoom2 { get; set; }
    }
}
