//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int id { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<decimal> monthlySalary { get; set; }
        public string insuranceCode { get; set; }
        public string place { get; set; }
        public Nullable<int> idEvent { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Insurance_Types Insurance_Types { get; set; }
    }
}
