//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class NangLuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NangLuong()
        {
            this.DienBienNangLuongs = new HashSet<DienBienNangLuong>();
        }
    
        public int id { get; set; }
        public string SoQD { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idContract { get; set; }
        public Nullable<double> LuongHienTai { get; set; }
        public Nullable<double> LuongMoi { get; set; }
        public Nullable<System.DateTime> signDay { get; set; }
        public Nullable<System.DateTime> upDay { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DienBienNangLuong> DienBienNangLuongs { get; set; }
    }
}
