//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRoll
    {
        public int code { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<double> wordDay { get; set; }
        public Nullable<double> dayOff { get; set; }
        public Nullable<double> withofleave { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<double> allowance { get; set; }
        public int id { get; set; }
        public Nullable<int> totalDayOfMonth { get; set; }
        public Nullable<double> overTime { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
