//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_NHANSUEntities : DbContext
    {
        public QL_NHANSUEntities()
            : base("name=QL_NHANSUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Allowance> Allowances { get; set; }
        public virtual DbSet<BoardSalary> BoardSalaries { get; set; }
        public virtual DbSet<BoardSalaryDe> BoardSalaryDes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Insurance> Insurances { get; set; }
        public virtual DbSet<Insurance_Types> Insurance_Types { get; set; }
        public virtual DbSet<Lever> Levers { get; set; }
        public virtual DbSet<Nation> Nations { get; set; }
        public virtual DbSet<PayRoll> PayRolls { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<StaffJoinAllowance> StaffJoinAllowances { get; set; }
        public virtual DbSet<ViewNVcb> ViewNVcbs { get; set; }
        public virtual DbSet<NangLuong> NangLuongs { get; set; }
        public virtual DbSet<DieuChuyen> DieuChuyens { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<DienBienNangLuong> DienBienNangLuongs { get; set; }
    }
}
