//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int id { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<decimal> salary1 { get; set; }
        public Nullable<System.DateTime> dayPayment { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
