//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffJoinAllowance
    {
        public int id { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idAllowance { get; set; }
    
        public virtual Allowance Allowance { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
